---
title: |
  How does visual information influence social interactions?
code-repo: |
  For replication, go to: <https://github.com/DamonCharlesRoberts/visual_information_and_political_participation>.
author:
  - name: Damon C. Roberts
    email: damon.roberts-1@colorado.edu
    orcid: 0000-0002-4360-3675
    title: PhD Candidate
    affiliations:
      - id: CU
        name: University of Colorado Boulder
        department: Political Science
        address: 333 UCB
        city: Boulder
        region: CO 
        postal-code: 80309-0333
abstract: |
  Though talking politics with others have a number of positive effects for a number of democratic outcomes, skepticism remains of whether it has any benefits. While some literature suggests that conversations about politics can encourage formal democratic participation and can reduce political polarization, other work argues that the context around the conversation neutralize these benefits. Some of this literature suggests that conversations with out-partisans are quite unlikely as we are motivated to avoid such conversations. The mechanism by which we know prior to a conversation about another's political viewpoints are quite unclear. I argue in this chapter that we rely on simple visual cues to help us make inferences about another's political views; specifically color. Such simple information, though error-prone, has important behavioral implications. Beyond that, I argue that those snap-judgments made have potent influences upon the content and effects of the conversation if it happens. This snap-judgment model of political information processing argues that we cue on simple visual information like the color of clothing people wear and that shapes the tendency to engage in conversations and our feelings about the conversation after it is over. Not only does this model have implications for the role that color plays in signaling partisanship in the United States but it also has implications for our understanding of the mechanisms underlying the limited benefits that political conversation has on democratic outcomes.

bibliography: "../../../assets/references.bib"
format:
  hikmah-pdf:
    # Spit out in drafts directory
    latex-output-dir: "../../out/prr"
    # Use biblatex-chicago
    biblatex-chicago: true
    biblio-style: authordate
    biblatexoptions: 
      - backend=biber
      - autolang=hyphen
      - isbn=false
      - uniquename=false
    geometry:
      - top=1in
      - bottom=1in
      - left=1in
      - right=1in
      - heightrounded
    linestretch: 2
    fontsize: 12pt
nocite: |
  @quarto
execute:
  echo: false
  warning: false
  message: false
  cache: false
params:
  replicate: true
---

{{< pagebreak >}}

# Introduction

Do politically-relevant colors predict our propensity to engage in political conversations? Does this have downstream consequences for informal political participation and for affective polarization? Conversations about politics are often considered to be a central component of political behavior in American democracy [@huckfeldt_2007_ohpb]. Evidence suggests that political conversations encourage many different forms of participation in politics [@verba_et-al_1995_hup;@klofstad_2007_prq], increase one's levels of political knowledge [@mcclurg_2003_prq], and is even capable of buffering animosity toward out-partisans [@levendusky_stecula_2021_cup]. Though it has these benefits, the existing literature in political science demonstrates that social groups, and particularly partisanship, motivate vast amounts of political behavior as well. One primary way that this manifests is the degree to which we interact with out-partisans relative to co-partisans. Rooted in classic social identity theory, the argument is that we have these tendencies out of a motivation to defend our pre-existing beliefs [@kunda_1990_pb;@jost_et-al_2022_n].

Evidence of motivated reasoning manifests in a number of political [see @iyengar_westwood_2015_ajps] and even non-political [@nicholson_et-al_2016_pb] contexts. There are a number of consequences for this. First, many of our networks with whom we talk to regularly are constructed of close friends and family and we are often reluctant to harm those relationships through disagreement; therefore, organic and meaningful conversations about politics are relatively uncommon [@mutz_2002_apsr;@mutz_2006_cup]. Second, outside of our family and close friends, our networks are quite politically homogenous [@huckfeldt_sprague_1987;@butters_hare_2022_pb]. Third, evidence suggests that even if we are offered information from other political perspectives, we do not try to integrate it with our prior beliefs [@kunda_1990_pb;@lodge_taber_2013_cup] and the benefits of any exposure to such information do not last very long [@levendusky_stecula_2021_cup] as a result.

Though the literature is mixed on whether cross-partisan conversations are beneficial for formal participation and reducing affective polarization, much of the evidence for their drawbacks start from the position that we enter a conversation with motivated reasoning already active. While this offers leverage to researchers to determine whether we can overcome motivated reasoning, it muddies our ability to make examine deliberation's effects on affective polarization and participation. In response, some have put in effort to examine the ways in which individuals enter political conversations without prior information about another's political viewpoints. @carlson_settle_2022_cup argue that we can use the clothing of others to make an informed guess about the partisanship of a potential discussion partner. For example, it would probably be reasonable to assume that someone wearing a Patagonia jacket would be a Democrat and someone wearing a Carhartt jacket would be Republican. Just these assumptions based on the appearance of another person can lead someone to avoid a potential political conversation with others these scholars conclude [@carlson_settle_2022_cup]. This fits with a well-established literature in political psychology that suggests that there are cultural differences between partisans [@hetherington_weiler_2018_hmh] and a rich literature in social psychology demonstrating the role of social groups, more broadly, which have visual cues that we cultivate for ourselves and detect in others [see @pietraszewski_et-al_2015_c].

In this chapter I argue that the visual information required to encourage political conversation can be simple, yet potent. I argue that this visual information need not necessarily be as complex as things like the branding of someone's clothes. While that is visual information, it is rather complex visual information as it requires not only brand recognition but also requires prior knowledge and accessible information associating a particular brand with a partisan position. Though it seems as though every company has developed *some* sort of reputation because they have taken some sort of stance on a issue wrapped up in a culture war, not everyone follows the latest source of political outrage all of the time [MARCUS PRIOR BOOK]. Colors convey significant amounts of information by themselves. As an almost universal form of visual information, color is among the fastest types of information that humans process [see @ames_et-al_2012_ohsn]. Colors are deeply embedded into a number of schemas that organize our previous experiences which enable the processing and reacting to new information [see @cimbalo_et-al_1978_jgp]. Colors not only have strong associations with our affective state [see @mehta_zhu_2009_s;@elliot_maier_2012_aesp], but they also convey significant amounts of information about social groups [@pietraszewski_et-al_2015_c].

As colors provide potent information about salient social groups, I argue that politically-relevant colors, red and blue, are important informational cues that individuals rely upon to evaluate others and their ideological positions when politics is salient to them. As parties increase their efforts to stake out their positions and to highlight their distinctions, the colors they use are increasingly used as a visual cue and heuristic to convey one party versus the other [@elving_2014_npr]. The implication of this argument not only explains the ways in which colors may be a source of information that people can use to decide whether or not to participate in a conversation about politics with someone else, but also it applies a model and applies a particular type of political information that explains the cognitive processes underlying the potential efficacy of political conversations on depolarization. This chapter demonstrates that even simple information that we as researchers and citizens often take for granted has significant downstream effects on our political attitudes and behaviors.

In the following section I lay out the fundamental theories and concepts in neuroscience and psychology that I build my argument upon. After I lay out these fundamental ideas, I then elaborate on my snap-judgment model of political information processing that leaves me with a number of predictions about how people will form attitudes and behave under different conditions. While doing so, I discuss the implications of this model upon our existing understanding in political science about the effects of political conversations upon political polarization.

# The cognitive architecture of attitudes and the role of colors

While the formation of attitudes is an extremely complex process, there are a few themes. The first among them is that attitude formation, which is to evaluate an object we interact with out in the world, is heavily dependent on drawing connections between things that we have experienced in our past, our memories [@fazio_2007_sc]. The second theme is that these memories are, they themselves, connected to a vast network of information that not only includes other memories but are multi-dimensional in nature [@kahana_et-al_2022_ohhum]. This complex web of associations are often referred to as a cognitive schema [@lodge_taber_2013_cup]; I will use this terminology as well moving forward as a shorthand. 

The first theme of research on attitudes suggests that attitudes are tightly connected to memories [@fazio_2007_sc;@cunningham_et-al_2012_ohsn]. Attitudes formed on current objects are the result of a complex network of memories that have a number of important valanced, affectively positive or negative, ties [@cunningham_et-al_2012_ohsn]. That is, memories are not just a encyclopedic encoding of an experience. Central to memory is the encoding of emotion (or affect). Experiences that we have that evoke strong affective responses tend to be stronger memories that we tap into more often and they tend to last longer than those that produced weaker emotions [@kensinger_fields_2022_ohhum]. Recent experiences and those that are closely related by similarity are also fundamental contributors to the strength of a memory and its centrality in our vast network of information we rely upon to evaluate new information [@kahana_et-al_2022_ohhum].

As I mentioned before, these connections to other forms of information, other memories, and their branches form a cognitive schema. Cognitive schemas are not only useful for allowing us to form opinions on whether we like eating Broccoli or not, but are also highly influential in prediction. We do not just rely upon the schema of the object itself, but we can also utilize auxillary information related to the object [@fazio_2007_sc;@kahana_et-al_2022_ohhum]. This is highly useful in situations involving uncertainty. That is, where we are unsure about an object, we can rely on this complex network of memories to find memories about similar objects to help us get a sense of how we should respond to an object [@kahana_et-al_2022_ohhum]. This complexity also is quite efficient. Though our memories and formation of attitudes rely on information that is multidimensional, this allows for us to tap into a vast amount of features about different memories to help us form some evaluation about a current experience -- even when we are unsure about what exactly we are experiencing[@fazio_2007_sc].

One set of dimensions that are highly influential in attitude formation due to their tendency to simplify our understanding of the world is information about social groups. Research suggests that we are attuned to information that has implications for social groupings when we are experiencing something new [@santavirta_et-al_2023_n]. For over five decades, social psychologists have been building strong evidence suggesting that we rely on social groups to simplify our understanding of the world and that the social groups we belong to are heavily influential in our attitude formation and resulting behaviors [TAJFEL]. A rich literature in nueroscience, referred to here as "social neuroscience" has connected these streams of work on attitude formation from a neurosicientists' focus on congitive schemas with that of social psychologists. This rich literature has demonstrated that our efficient cognitive schemas often encode information about social groups as part of our multidimensional construction of memories [@santavirta_et-al_2023_n].

Tying it all back to color, one such example of the centrality of social group information as a dimension by which we form and store attitudes is through the use of color to reflect things like sports team affiliations and gang memberships [@pietraszewski_et-al_2015_c]. Colors as information come with a lot of baggage [@cimbalo_et-al_1978_jgp]. For example, colors like red are associated with anger and arousal while blue is associated with happiness [@elliot_maier_2012_aesp;@dandrade_egan_1974_ae]. Beyond the affective information that colors provide, they are widespread and efficient cues that help us connect information. Some literature suggests that we can process (absorb, process, and contextualize) color in as little as 33 milliseconds[@ames_et-al_2012_ohsn]. This partly occurs as result of the fact that we process colors automatically and pre-consciously [@mehta_zhu_2009_s]. Due to this, we also tend to unconsciously embed information about the color of an object when processing information. The theories on why this occurs are varied, but one intuitive explanation comes from a evolutionary biology perspective: we expect that particular fruits or animals should be of a certain color or of a certain shape, variation from that triggers a suspicion that there might be something wrong and we should avoid it [see @norman_et-al_2012_ohsn;@kahana_et-al_2022_ohhum]. As colors provide an important role for an individual's survival, they are processed efficiently and are often a central dimension included in a memory. With these features, colors are not auxillary forms of information that are encoded with an experience. Rather, they are universal and potent.

Here I summarize some of the fundamental concepts that I build upon to explain the role of color in depolarization and poltical conversations. (1) Memories are highly involved in attitude formation; (2) and are multidimensional in that they contain large amounts of different information. (3) One such form of information contained within them is the affect-laden valence that encodes whether experience with an object was positive or negative. (4) All of these memories are organized into a large and complex network of other memories that each have their associations as well that I refer to as a cognitve schema. (5) We tap into the information contained in our cognitive schema to evaluate objects that we are currently interacting with by finding similar prior experiences and using the encoded information with that prior experience and other associated prior experiences. (6) As this is an extremely complex and voluminous set of information, we need to rely on various shortcuts to help evaluate objects we are interacting with quickly. (7) One such form of information that we rely upon is information about social groups. (8) However, this too is quite complex so we can even rely simple visual information such as color to help cue us toward group membership. (9) Colors are not just something we interact with but they also are heavily involved in our memories and as a result can act as a source of information to access in our cognitive schema. (10) In fact, as an almost universal form of information that is efficiently processed, we can use colors to come to pre-conscious evaluations of a current object and therefore have the potential to heavily shape what paths in a cognitive schema we access and ultimately the attitude we form.

# Predicting the role of color in political attitude formation and behavior

Evidence suggests that political parties are an important social group to people. While people may have a number of social group memberships that may cross-cut eachother, one's membership with either the Republican or Democratic party appears to increasingly align with other identities (e.g., christian versus not religious, lives in the countryside or a city-dweller) [@mason_2018_cup]. As one's partisan identification is more central to people's self-conception, individuals in the United States are more invested in protecting their partisanship as it subsumes other characteristics that make them who they are [@mason_2018_cup]. As a result, we are seeing more and more political polarization due to this strong affective desire to protect their group [@mason_2018_cup;@iyengar_et-al_2019_arps; see also @iyengar_et-al_2012_poq]. For those that are not heavily engaged in politics or are reluctant to participate in *partisan* politics, specifically, many are still functionally partisan; however, they identify as an "Independent" as a result of their distaste for the hyperpolarized nature that characterizes contemporary politics in the United States and not for their moderate policy positions [@klar_krupnikov_2016_cup]. 

One result of the growing centrality of partisanship as an identity for individuals in the United States is that we are seeing more in-and-out-group oriented behavior based on partisanship both in and outside of political contexts. In political contexts, individuals are relatively accurate and willing to assume the partisan affiliation of a political candidate with ***no*** prior information on the candidate except for looking at their physical characteristics -- Republican candidates are associated with more "masculine" physical features [@olivola_et-al_2012_spps]. Relative to other significant social groups in the United States, animosity directed toward the other party, abstractly, is stronger than the willingness to express animosity toward racial and ethnic groups [@iyengar_westwood_2015_ajps].^[Though, see @westwood_peterson_2022_pb.] This goes so far as to generate "empathy gaps" where individuals exhibit lower levels of empathy for out-partisans experiencing the negative effects of a policy that they and their party supported [@allamong_peterson_2021_pp]. The effects are that moderate candidates cannot win because many voters see the stakes as too high and often choose "stronger" partisans that have a higher chance of getting everyone within the party to turn out to vote [@utych_2020_es]. The effects of partisan membership extend beyond just political contexts where individuals are less likely contact people from the other party on a dating app [@nicholson_et-al_2016_pb].

This group-based behavior on the basis of partisan identity has led to a number of important implications relevant to the present study. Firstly, the two parties are heavily engaged in differentiating themselves from one another [@enders_2021_jop] and that this even shows up in how members of Congress interact or do not interact with out-partisan colleagues [@dietrich_2021_pa]. Second, there are cultural differences tied to the parties that are recognizable to the average individual [@hetherington_weiler_2018_hmh]. Third, the visual elements of politics and of these brands are important as they provide significant amounts of information about group membership through the careful efforts made by the parties to curate a "brand" [see @grabe_bucy_2009_oup;@lilleker_2019_pm;@messaris_2019_pm].

How does partisanship influence attitude formation? Merging some of the important themes in social neuroscience, @lodge_taber_2013_cup argue that political attitudes are formed by using cognitive schemas that are heavily biased toward information that fits with attitudes shared by co-partisans. This motivated reasoning is pervasive beyond politics [see @kunda_1990_pb], however, politics is a strong case study for that phenomenon. This means that politics is not just expressive [see @huddy_et-al_2015_apsr], but that it deeply influences our pre-conscious processing of new political information [@lodge_taber_2013_cup]. Rather than us consuming new political information and folding it into our existing beliefs [@zaller_1992_cup], it often dictates a behavioral response that immediately follows our valanced evaluation of the object to either ignore the information coming in or to only use the information as a foil to make a defensive counterpoint to it [@taber_lodge_2006_ajps].

Using this knowledge as a foundation for the snap-judgment model of political information processing, I argue that politically-relevant colors are one such form of information that have heavily influences on what types of information we process and encode and it the directs motivations that we have even in non-political circumstances. The snap-judgement model would suggest that exposure to an object containing politically relevant colors -- red and blue, in particular -- should activate a particular set of memories that have those and related colors encoded with it. This makes the paths to particular memories and associated memories "hot." As the literature on cognitive schemas suggest, these memories are not just memories about color but that they have important affective valence associated with them [@cimbalo_et-al_1978_jgp]. 

Though colors have generalized affective associations, they also are multi-dimensional and contain associations in particular contexts like other memory objects. This affective valence is not simply "happy" or "sad" [e.g., @cimbalo_et-al_1978_jgp], but is complicated by the association of those colors with particular party brands -- namely that Republicans are more associated with the color red and Democrats with the color blue in the United States. If one has antagonistic attitudes toward Republicans but see Democrats in a positive light, the color red when politics is salient to them should lead them to have a negatively valenced attitude toward the object while the color blue would lend itself to a positive one. I am agnostic toward the particular discrete emotions it evokes as some research in affective neuroscience also suggests that initial evaluations are also agnostic about discrete emotions and are usually limited to valance (positive or negative) until one has more information. This fits with the prevailing literature on attitude formation as well. As we may have memories associating Republicans with some type of positive emotion, we likely just average across those evaluations to come up with "positive" prior experiences as opposed to averaging across discrete emotions (e.g., joyful versus happy) to come up with a discrete emotion to encapsulate all prior experiences with Republicans.

Motivated reasoning suggests that once these paths are activated and the affective valance they induce are active, we often have one of two motivations -- to either avoid further interaction with the thing that makes you feel bad or to keep interacting with it in hopes that you will have a positive experience [@valentino_et-al_2011_jop;@norman_et-al_2012_ohsn;@taber_lodge_2006_ajps; see also @sander_2013_chhan;@dror_2017_er]. As discussed in the opening pages, the particular political behavior I focus on here is a willingness to engage or disengage in political conversations. Conversations about politics are viewed to be a promising avenue by which we can reduce societal divisions that we are currently observing in the United States [see @levendusky_stecula_2021_cup;@levendusky_2023_ucp]. The snap-judgement model would answer this elusive question with "it depends." 

So far, the snap-judgment model gives the impression that if one sees someone with a red hat and immediately think "that person is probably a Donald Trump suppporter, and a Republican", my discussion of the model so far would indicate that there is a strong motivation to disengage and avoid the conversation. If it was someone wearing a blue hat and someone's initial impression is "that person must be a Democrat like me," then rather than being motivated to disengage, they may be more willing to participate in the conversation. These expectations align -- though they expand upon the way we come to those expectations -- with the vast majority of the literature on informal political participation and political deliberation. We are not always able to avoid a conversation, however.

Despite some of our best efforts, we often are roped into a conversation with another person that we may disagree with. However, so far, we have already formed a snap-judgment about them. We either reluctantly found ourselves caught in a conversation with someone that identifies with the other political party or are thankfully in a conversation with someone we agree with and were lucky to not get caught in the conversation with the other folks who you were concerned you would disagree with. When new information comes about from this conversation, our initial snap-judgment likely changes. We either become more sure that we were initially right to avoid the person with the blue or red hat or we now might think "huh, I may have judged a book by its cover and this wasn't as bad as I had originally feared." The snap-judgment model builds upon existing work on the implications of polarization on political conversations by highlighting a mechanism whereby individuals may have formed a snap-judgment that can be quite incorrect as a result of relatively unreliable heuristics -- not everyone who wears a red hat at any given social function is doing so because they are a Republican. Though these snap-judgments are quite error prone, they are heavily influential in the final encoding of the experience as positive or negative. As the model has highlighted so far, these snap-judgments can dictate whether you engage in the conversation in the first place and if you are stuck in one anyhow, it dictates your motivation in the conversation: to find information that fits with the snap-judgment you had already formed. 

Snap-judgments have even more influence than likelihood of conversation or motivation at the outset to agree or disagree with everything a discussion partner says, but also the motivated cognitive path they have you access also requires significantly more work for you to change your mind if the new information does not comport with your snap-judgment. As the snap-judgment is derived from a particular path that leads to an evaluative position -- "I have a bad feeling about this" or "this should be engaging" -- the information that does not fit with the current path we are on must successfully move us onto a contiguous path but one that has more positive associations. As these are likely rarer [see @taber_lodge_2006_ajps;@lodge_taber_2013_cup], countervailing information has its work cut out for it. Even if we can leave the conversation feeling more positively, we have a strong bias to encode memories with negative evaluations [@norman_et-al_2012_ohsn; see also @lodge_taber_2013_cup]. Furthermore, the likelihood that this memory "sticks" and remains an accessible path that is not forgotton is quite low as well unless we have other similar experiences [@kahana_et-al_2022_ohhum] that challenge our pre-existing feelings on having conversations with those outside of politics.


@fig-theory provides a visual representation of the mechanisms involved in the snap-judgment model. The conclusions from this model largely align with pre-existing findings. However this model provides a few novel contributions. First, the model demonstrates how even simple visual cues like color can have deep and long-lasting (in terms of the duration of an experience) effects on behavior and attitudes. Second, the model combines foundational knowledge from social neuroscience, affective neuroscience, social psychology, and political psychology to outline the mechanisms at the root of question that has yielded quite perplexing empirical evidence making it difficult to identify a clean set of conclusions. 

To be clear, @tbl-hypotheses outlines a set of testable hypotheses generated from this model when applied to color as a set of visual information to prime reactions to a potential conversation about politics. First, I expect that people notice the color of the clothing that people are wearing in the first place. When we are in situations of anxiety, which often accompany the prospect of having a conversation with a new person about politics [see @carlson_settle_2022_cup], we often seek out whatever information we can get our hands on [@marcus_et-al_2000_ucp]. Second, I expect that when we are primed to think of politics and think of the colors red and blue in terms of politics, rather than say a sports team, people are less likely to want to have a conversation with an out-partisan [@huckfeldt_sprague_1987]. Third, if we have the conversation anyhow, we are more likely to report significant amounts of discomfort in the conversation if we are unable to find anything to agree on or to find a common or shared identity beyond our partisan identification [@santoro_broockman_2022_sa]. Fourth, on the other side of the coin, if the conversation goes in a direction where we can find shared ground, then we are more likely to find something positive about the conversation [@santoro_broockman_2022_sa]. And finally, if we have a conversation that went better than expected, measures of affective polarization are likely to be lower relative to those that had a conversation go just about what we had expected or worse. The following section outlines a research design to examine whether there is empirical evidence supporting the hypotheses outlined in @tbl-hypotheses that were derived from the snap-judgment model.

{{< include ../../../assets/_theory.qmd >}}

+--------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Hypotheses   | Expectation                                                                                                                                                                                                                                                               |
+==============+:=========================================================================================================================================================================================================================================================================:+
| $H_1$        | People notice the color of clothing a potential conversation partner is wearing                                                                                                                                                                                           |
+--------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| $H_2$        | When primed to think about politics, people are less likely to want to have a conversation with someone wearing a blue shirt if they are a Republican and  a red shirt if they are a democrat.                                                                            |
+--------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| $H_3$        | When learning more information about someone that fits with our initial impression, our motivation of engagement or disengagement is stronger than if the information were incongruent with our initial impressions.                                                      |
+--------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| $H_4$        | When learning more information about someone that does not fit with our initial impression, the new information can shift our motivations to have the conversation or to disengage. However, this difference is smaller than if both forms of information were congruent. |
+--------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| $H_5$        | People that find common ground despite first impressions are likely to exhibit lower levels of affective polarization than they had prior.                                                                                                                                |

: Summary of hypotheses {#tbl-hypotheses}

<!--
  NOTE: ADD SOMETHING ABOUT ASYMMETRIC POLARIZATION
-->


# Study 1

## Study design

Study 1 seeks to address $H_1$ and $H_2$. In study 1, I recruit participants from ***[YouGov/MTURK]***. First I ask participants a number of questions about their demographic background (i.e., age, gender identity, education, and income). I additionally present them with a battery to measure conflict avoidance and to measure the degree to which they are willing to spark up conversations with strangers as potential confounds. 

After getting some background information on my participants, I randomly split the sample into two conditions. The first condition is a "political prime" condition and the second is a "no political prime" condition. For the participants in the political prime condition, I ask them a number of questions about their political attitudes. This includes questions about their partisan identification and their attention to politics. This is designed to make politics salient for them. Those assigned to the second condition, no political prime, participants are asked these questions after the main treatment, but not before. This is designed to test the scope conditions of the relevance of clothing color in conversation when politics has not been primed.

In the main treatment of the study, participants are assigned to one of two conditions. In both conditions, participants are instructed "You will have a conversation with this person". In these instructions, I take care to not state that this is going to be a "political conversation" or a "conversation about politics". I see these instructions as substantively different as the latter phrasings prime politics. The goal is that the priming (or no priming) done before this treatment will be what is making politics salient or not.

Below those instructions, participants are shown an image of a person with either a blue or a red shirt. The first hypothesis would suggest that there should be differences in how willing someone would be to have a conversation between the conditions if they were primed with politics. For those not primed with politics beforehand, we should expect that the color of the shirt should not matter and for there to not be any substantively different levels of willingness to have that conversation between the red shirt, blue shirt conditions; the color of the shirt is not particularly relevant information.

The second hypothesis would suggest that those given the political prime would be more willing to have a conversation with someone who is wearing the color affiliated with their partisanship (e.g., Democrats more willing to have conversations with a discussion partner with a blue shirt than a red shirt) and less so with those who is not. Those in the non-political priming conditions, we should expect that there would be no real substantive difference between conditions as politics is not primed and the color of the shirt should have no significant meaning to them.


## Methods

```{r}
#| label: simulate-data
#| eval: false
int_samples <- 1000
list_n <- c(100, 150, 200, 250)

lm_dem <- lm(willing ~ treatment + treatment * prime) # democrat subsample
lm_rep <- lm(willing ~ treatment + treatment * prime) # republican subsample
```

## Results

# Study 2

## Study design

The setup for Study 2 is largely the same. Like in Study 1, I ask participants a number of questions about their demographic background and ask them about conflict avoidance and willingness to have conversations with strangers. As well as Study 1, I randomly split the sample into two conditions. A political prime and a no political prime condition. The purpose of doing this is not necessarily to prime politics anymore but is done more so for counterbalancing so that I am not systematically introducing post-treatment bias nor am I strengthening the effects of the treatment through systematically priming politics. Like in Study 1, I instruct participants that they will be having a conversation with someone and will show them someone wearing either a red or a blue t-shirt.

Study 2 is different in that below the image I now include that person's policy preferences. Below the image, there is a "profile" for this person that describes their political positions by listing their party identification, whether they are supportive of universal basic income, abortion, and gun control. What varies in the four conditions is first whether the person is wearing a blue or a red shirt. The second dimension that the conditions vary on is whether that profile of political attitudes match with the presumed partisanship affiliated with their shirt color. For example, a participant seeing a discussion partner with a red t-shirt that identifies as a Democrat, is supportive of UBI, is pro-choice, and is supportive of gun control would be considered an incongruent condition as opposed to the same discussion partner with the red t-shirt that identifies as a Republican that is not supportive of UBI, is pro-life, and is not supportive of gun control.

I chose these particular policies for a number of reasons. The first reason being that these policies are hot-button issues. While some skeptics of my research design may be concerned with me activating strong valenced responses, I argue that these choices increase the external validity of my study in that it is realistic that most people have *some* opinion (support or do not support) on these issues. In addition to external validity, I would argue that these are the sorts of policies that my participants would have some opinion on and would be most concerned discussing with other people. As these are polarized issues, these are the sorts of policy issues that people are concerned about discussing with others. They are less concerned about talking politics when discussing something like a local zoning law that limits the number of unrelated people that can not live with each other (save for perhaps Boulder, Colorado).

After seeing this profile, participants are asked whether they are willing to have a conversation with this person. I still should expect for $H_2$ to hold in that Democrats will be more willing to talk with those wearing blue shirts and Republicans will be more willing to talk to those in red shirts. However, I should expect for the degree to which this occurs will be limited based upon whether their stated partisan identification and policy preferences to be congruent. I suspect for those that have political attitudes that are incongruent with the respondents' will recieve less support than those that have congruent policy attitudes. However, I suspect that those wearing shirts that are incongruent but with congruent policy preferences will be less popular as a potential discussion partner than one with both a congruent shirt and policy preferences. The snap-judgment model suggests that we are capable of overwriting our initial impressions. However, we are limited in our ability to do so.

## Methods

## Results

# Discussion

{{< pagebreak >}}