---
title: |
  How does visual information influence social interactions?
code-repo: |
  For replication, go to: <https://github.com/DamonCharlesRoberts/visual_information_and_political_participation>.
author:
  - name: Damon C. Roberts
    email: damon.roberts-1@colorado.edu
    orcid: 0000-0002-4360-3675
    title: PhD Candidate
    affiliations:
      - id: CU
        name: University of Colorado Boulder
        department: Political Science
        address: 333 UCB
        city: Boulder
        region: CO 
        postal-code: 80309-0333
abstract: |
  Though political deliberation benefits those often excluded from politics, some argue that many individuals avoid such situations in an age of hyper-partisanship and affective polarization. Existing literature on this topic argue that individuals often seek to avoid uncomfortable situations that are caused by disagreement about politics. The outcomes of such motivations are often thought to increase affective polarization and to have negative participatory impacts for those who are often excluded or feel unwelcome in politics. Much of this work assumes that people know the partisanship of potential discussion partners and avoid those who are known to be out-partisans. For those that are strangers, some evidence suggests that we often can rely on cultural stereotypes of the other party to help us assume the partisanship of this potential discussion partner. This project argues that even more simple visual information can and is used by individuals to decide whether or not to engage in a discussion with another and can shape the outcomes of a conversation. It lays out a cognitive mechanism explaining how individuals make decisions to engage in a conversation and the limits by which deliberation may buffer political polarization.
bibliography: "../../../assets/references.bib"
format:
  hikmah-pdf:
    # Spit out in drafts directory
    latex-output-dir: "../../out/prr"
    # Use biblatex-chicago
    biblatex-chicago: true
    biblio-style: authordate
    biblatexoptions: 
      - backend=biber
      - autolang=hyphen
      - isbn=false
      - uniquename=false
    geometry:
      - top=1in
      - bottom=1in
      - left=1in
      - right=1in
      - heightrounded
nocite: |
  @quarto
execute:
  echo: false
  warning: false
  message: false
  cache: false
params:
  replicate: true
---

{{< pagebreak >}}

# Introduction

Do politically-relevant colors predict our propensity to engage in political conversations? Does this have downstream consequences for formal political participation and for affective polarization? Conversations about politics are often considered to be a central component of political behavior in American democracy [@huckfeldt_2007_ohpb]. Evidence suggests that political conversations encourage many different forms of participation in politics [@verba_et-al_1995_hup;@klofstad_2007_prq], increase one's levels of political knowledge [@mcclurg_2003_prq], and is even capable of buffering animosity toward out-partisans [@levendusky_stecula_2021_cup]. Though it has these benefits, the existing literature in political science demonstrates that social groups, and particularly partisanship, motivate vast amounts of political behavior as well. One primary way that this manifests is the degree to which we interact with out-partisans relative to co-partisans. Rooted in classic social identity theory, the argument is that we have these tendencies out of a motivation to defend our pre-existing beliefs [@kunda_1990_pb;@jost_et-al_2022_n].

Evidence of motivated reasoning manifests in a number of political [see @iyengar_westwood_2015_ajps] and even non-political [@nicholson_et-al_2016_pb] contexts. There are a number of consequences for this. First, many of our networks with whom we talk to regularly are constructed of close friends and family and we are often reluctant to harm those relationships through disagreement; therefore, organic conversations about politics are relatively uncommon [@mutz_2002_apsr;@mutz_2006_cup]. Second, outside of our family and close friends, our networks are quite politically homogenous [@huckfeldt_sprague_1987;@butters_hare_2022_pb]. Third, evidence suggests that even if we are offered information from other political perspectives, we do not try to integrate it with our prior beliefs [@kunda_1990_pb;@lodge_taber_2013_cup] and the benefits of any exposure to such information do not last very long [@levendusky_stecula_2021_cup] as a result.

Though the literature is mixed on whether cross-partisan conversations are beneficial for formal participation and reducing affective polarization, much of the evidence for their drawbacks start from the position that we enter a conversation with motivated reasoning already active. While this offers leverage to researchers to determine whether we can overcome motivated reasoning, it muddies our ability to make examine deliberation's effects on affective polarization and participation. In response, some have put in effort to examine the ways in which individuals enter political conversations without prior information about another's political viewpoints. @carlson_settle_2022_cup argue that we can use the clothing of others to make an informed guess about the partisanship of a potential discussion partner. For example, it would probably be reasonable to assume that someone wearing a Patagonia jacket would be a Democrat and someone wearing a Carhartt jacket would be Republican. Just these assumptions based on the appearance of another person can lead someone to avoid a potential political conversation with others [@carlson_settle_2022_cup]. This fits with a well-established literature in political psychology that suggests that there are cultural differences between partisans [@hetherington_weiler_2018_hmh] and a rich literature in social psychology demonstrating the role of social groups, more broadly, which have visual cues that we cultivate for ourselves and detect in others [see @pietraszewski_et-al_2015_c].

I argue that the visual information required to encourage political conversation can be simple, yet potent. I argue that this visual information need not necessarily be as complex as things like the branding of someone's clothes. While that is visual information, it is rather complex visual information as it requires not only brand recognition but also requires prior knowledge and accessible information associating a particular brand with a partisan position. Colors convey significant amounts of information by themselves. Visual information such as color is among the fastest types of information that humans process [see @ames_et-al_2012_ohsn]. Colors in particular are deeply embedded into a number of schemas that organize our previous experiences which enable the processing and reacting to new information [see @cimbalo_et-al_1978_jgp]. Colors not only have strong associations with our affective state [see @mehta_zhu_2009_s;@elliot_maier_2012_aesp], but they also convey significant amounts of information about social groups [@pietraszewski_et-al_2015_c].

As colors provide potent information about salient social groups, I argue that politically-relevant colors, red and blue, are important informational cues that individuals rely upon to evaluate others and their ideological positions when politics is salient to them. The implication of this argument is that when individuals make such connections, we can predict behavioral motivations and outcomes depending on one's valanced associations with those colors in a political context. The motivations to engage or avoid in political conversations generated from such simple visual information can have serious implications for political participation and polarization.

In the following sections I elaborate on the cognitive processes that lend themselves to such a mechanism. After detailing the existing literature on this, I outline a snap-judgment model of political information processing that demonstrates the implications for propensity to engage in a political conversation and to reduce political polarization. Following that, I explore empirical evidence of this theory by performing an experiment.

# How colors convey membership to social groups

Attitudes are tightly connected to memories. Attitudes formed on current objects are the result of a complex network of memories that have a number of important valanced ties. These connections to other forms of information, other memories, and their branches form a cognitive schema. Cognitive schemas are not only useful for allowing us to form opinions on whether we like eating Broccoli or not, but are also highly influential in prediction. We do not just rely upon the schema of the object itself, but we can also utilize auxillary information related to the object. This is highly useful in situations involving uncertainty. That is, where we are unsure about an object, we can rely on this complex network of memories to find memories about similar objects to help us get a sense of how we should respond to an object.

A rich literature on social neuroscience disentangles cognitive schemas by focusing on the centrality that social groups play in them. For five decades, social psychologists are building an increasing large amount of evidence coming to a central conclusion: humans rely on our social groups we have ties with to help us gather information and form attitudes on new experiences. Existing research by social neuroscientists document this in our cognitive schemas. Research using an fMRI demonstrates that we do not just evaluate information as separate objects, but that we quickly process all dimensions of the information quickly and through the lens of social interaction.

In exploring the forms of visual information that are used to predict social groups, some research suggests that color plays a central part. This research suggests that individuals have a tendency to predict someone's social group based on the colors of clothing and other objects they have. This tendency also appears to be quite efficient. The ability to do so often is dependent on what social groups are salient, however, this seems to be a tendency that many people have. For example, we often are capable of concluding that someone is a fan of a particular sport team if they are wearing some article of clothing that has the colors of that team. However, we can be much more accurate in that conclusion when we see that person outside of a stadium on game day as opposed to some other time where that particular sport and team are less salient. 

As the political parties appear to be taking on distinguishable "brands", we may expect that the branding of the political parties can also act as a reliable visual cue to predict the partisan identification of another person when politics is salient.

# How the connection to social group membership motivates political behavior

{{< include ../../../assets/_theory.qmd >}}

# Research design

I recruit students from a large university in the southwestern region of the United States by posting advertisements and through word of mouth. Though it is a convenience sample, I expect that common demographic differences between a student-based convenience sample and the general population *do not* have consequences for the effect of the treatment upon my measured outcomes [@krupnikov_et-al_2021_cup].[^convenience_sample]

[^convenience_sample]: While color-blindness may be a factor influencing these effects and the rates of it are lower among a student sample, this is a different population of interest. I do not expect that racial and ethnic, socio-economic, or gender differences alone would cause differences in my treatment's effect.

The students who volunteer to participate in the study are emailed containing a link to a URL to the study. Students are informed that this is a "pre-screen for the study". In this "pre-screen", I ask participants about their demographics and a number of questions about their interest in politics, two feeling thermometers for Democrats and Republicans to be used to measure affective polarization, and their partisan identification. I purposely ask participants these questions *before* introducing the treatment as to make politics and partisan affiliations salient.

After completing these questions, participants participate in the first trial of the treatment. They are shown an image of a college-aged person wearing a t-shirt. This is a plain t-shirt, however, the color of that shirt is randomly chosen to be either red, blue, or white. Below the image, I ask participants whether they "would be willing to come to campus to have a conversation about politics with this person." After answering "yes" or "no", I ask participants to report their feelings toward Republicans and Democrats with two feeling thermometer scales. They are then debriefed and told that researchers will be following up with them in the next couple of weeks. 

One week later, participants will be contacted again via email with another link to a "follow-up to the pre-screening". This time, they will see the image again, however, there will be a "profile" for the person that lists their political viewpoints which are randomized to be either "Republican", "independent", or "Democrat". I explain below the image, above the profile, as being "more information that we've collected since they have completed the pre-screening for the study too." Below the profile, I ask participants again whether they would be willing to come to campus to have a conversation. I additionally ask them a third time about their feelings toward Republicans and Democrats through two feeling-thermometer scales.

After completing this second round, I debrief participants and inform them that the "potential discussion partner" was fictional. After explaining to them the necessity for deception, I provide information about how they can be compensated for participating in the study.

# Methods

# Results

# Discussion

{{< pagebreak >}}